resources:
  repositories:
    - repository: oneonone_cp_ciTemplates
      type: git
      name: ci-templates
      ref: v1.0.0

trigger:
  - pipeline

pool: agent-pool

extends:
  template: backend/main.yml@ci-templates
  parameters:
    AppName: 'trialanddemo'
    AppSourceDir: . 
    DeployTo:
      - qa
      - dev
