parameters:
  - name: AppName
    type: string
  - name: AppSourceDir
    type: string
  - name: AppNamespace
    type: string
    
jobs:
- job: build
  displayName: 'Build and Publish'
  steps:
  - script: |
      az login --identity
      az acr login --name $(AcrName)
    displayName: 'ACR Login'

  - task: Docker@2
    displayName: 'Docker build'
    inputs:
      command: 'build'
      Dockerfile: '${{ parameters.AppSourceDir }}/Dockerfile'
      repository: '$(AcrName)/${{ parameters.AppName }}'
      tags: '$(Build.BuildNumber)'
      
  - script: |
      docker push $(AcrName)/${{ parameters.AppName }}:$(Build.BuildNumber)
    displayName: 'Publish Image'

  - task: Docker@2
    displayName: 'Docker build celery'
    inputs:
      command: 'build'
      Dockerfile: '${{ parameters.AppSourceDir }}/Dockerfile.celery'
      repository: '$(AcrName)/${{ parameters.AppName }}-celery'
      tags: '$(Build.BuildNumber)'
      
  - script: |
      docker push $(AcrName)/${{ parameters.AppName }}-celery:$(Build.BuildNumber)
    displayName: 'Publish Celery Image'
  
  - script: |
      helm template \
            -f .helm/values.yaml \
            --set appVersion=$(Build.BuildNumber) \
            --set registry=$(AcrName) \
            --set appNamespace=${{ parameters.AppNamespace }} \
            .helm >> $(Agent.TempDirectory)/${{ parameters.AppName }}-mainfest.yaml
    displayName: 'Create Manifest'
            
  - task: PublishBuildArtifacts@1
    enabled: true
    displayName: 'Publish Manifest'
    inputs:
      ArtifactName: '${{ parameters.AppName }}-mainfest.yaml'
      PathtoPublish: '$(Agent.TempDirectory)/${{ parameters.AppName }}-mainfest.yaml'