parameters:
  - name: AppName
    type: string
  - name: AppSourceDir
    type: string

jobs:
- job: build
  displayName: 'Run Build'
  steps:
  - script: |
      az login --identity
      az acr login --name $(AcrName)
    displayName: 'ACR Login'
  - task: Docker@2
    displayName: 'Docker build'
    inputs:
      command: 'build'
      Dockerfile: '${{ parameters.AppSourceDir }}/Dockerfile'
      repository: '$(AcrName)/${{ parameters.AppName }}'
      tags: '$(Build.BuildNumber)'
  - script: |
      docker push $(AcrName)/${{ parameters.AppName }}:$(Build.BuildNumber)
    displayName: 'Publish Image'