parameters:
  - name: AppName
    type: string
  - name: AppSourceDir
    type: string
  - name: AppNamespace
    type: string

jobs:
  - deployment: deploy
    displayName: 'Deploy'
    environment: 'jc-infra-deploy'
    timeoutInMinutes: 15
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                az login --identity
              displayName: 'AKS Login'
                