parameters:
  - name: AppName
    type: string
  - name: AppSourceDir
    type: string
  - name: AppNamespace
    type: string
  - name: AksEnv
    type: string

jobs:
  - deployment: deploy
    displayName: 'Deploy'
    environment: 'jc-app-deploy-${{ parameters.AksEnv }}'
    timeoutInMinutes: 15
    strategy:
      runOnce:
        deploy:
          steps:
            - script: |
                az login --identity
                az aks get-credentials --resource-group jc-${{ parameters.AksEnv }}-spoke-rg --name jc-${{ parameters.AksEnv }}-spoke-aks --overwrite-existing --admin
              displayName: 'AKS Login'

            - task: DownloadPipelineArtifact@2
              displayName: 'Get helm Manifest'
              inputs:
                artifactName: '${{ parameters.AppName }}-mainfest.yaml'
                path: '$(Agent.TempDirectory)'

            - script: |
                kubectl apply -f $(Agent.TempDirectory)/${{ parameters.AppName }}-mainfest.yaml
                kubectl rollout status deployment/${{ parameters.AppName }} -n ${{ parameters.AppNamespace }} --watch=true --timeout=10m
              displayName: 'Deploy to AKS'