parameters:
  - name: AppName
    type: string
  - name: AppSourceDir
    type: string
  - name: AppNamespace
    type: string
  - name: DeployTo
    type: object
    default: [] 

variables:
  - group: jc-infra-vars
  - name: AcrName
    value: app123.azurecr.io
  - name: DOCKER_BUILDKIT
    value: 1

stages:
  - stage: Build
    displayName: 'Build and Scan'
    jobs:
      - template: build-publish.yml
        parameters:
          AppName: '${{ parameters.AppName }}'
          AppSourceDir: '${{ parameters.AppSourceDir }}'
          AppNamespace: '${{ parameters.AppNamespace }}'

      - template: scan-analyse.yml
        parameters:
          AppName: '${{ parameters.AppName }}'
          AppSourceDir: '${{ parameters.AppSourceDir }}'

  - stage: Deploy
    dependsOn: Build
    displayName: 'Deploy to Dev'
    jobs:
      - template: deploy.yml
        parameters:
          AppName: '${{ parameters.AppName }}'
          AppSourceDir: '${{ parameters.AppSourceDir }}'
          AppNamespace: '${{ parameters.AppNamespace }}'