parameters:
  - name: AppName
    type: string
  - name: AppSourceDir
    type: string
  - name: AppNamespace
    type: string
  - name: ProjectName
    type: string
  - name: ProjectKey
    type: string 
  - name: ApiURL
    type: string

variables:
  - group: jc-devops-vars
  - name: AcrName
    value: jcapp2025.azurecr.io
  - name: DOCKER_BUILDKIT
    value: 1

stages:
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    - stage: SonarOwaspGitleak
      displayName: 'Sonar, owasp & gitle scan'
      jobs:
        - template: sonar-owasp-gitleak.yml
          parameters:
            ProjectName: '${{ parameters.ProjectName }}'
            ProjectKey: '${{ parameters.ProjectKey }}'
          

  - stage: Build
    displayName: 'Build and Scan'
    jobs:
      - template: build-publish.yml
        parameters:
          AppName: '${{ parameters.AppName }}'
          AppSourceDir: '${{ parameters.AppSourceDir }}'
          AppNamespace: '${{ parameters.AppNamespace }}'

      #- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      - template: scan-analyse.yml
        parameters:
          AppName: '${{ parameters.AppName }}'
          AppSourceDir: '${{ parameters.AppSourceDir }}'
  # 

  
  - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/release/qa')) }}:
    - stage: Deploy_dev
      dependsOn: Build
      displayName: 'Deploy to Dev'
      jobs:
        - template: deploy.yml
          parameters:
            AppName: '${{ parameters.AppName }}'
            AppSourceDir: '${{ parameters.AppSourceDir }}'
            AppNamespace: '${{ parameters.AppNamespace }}'
            AksEnv: 'dev'


  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/release/uat') }}:
    - stage: Deploy_uat
      dependsOn: Build
      displayName: 'Deploy to UAT'
      jobs:
        - template: deploy.yml
          parameters:
            AppName: '${{ parameters.AppName }}'
            AppSourceDir: '${{ parameters.AppSourceDir }}'
            AppNamespace: '${{ parameters.AppNamespace }}'
            AksEnv: 'uat'

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    - stage: owaspzap
      dependsOn: Deploy_dev
      displayName: 'owasp-zap baseline scan'
      jobs:
        - template: owasp-zap.yml
          parameters:
            ApiURL: '${{parameters.ApiURL}}'
    
  

  