parameters:
  - name: AppName
    type: string
  - name: BuildSourceDir
    type: string

stages:
  - stage: Scan
    displayName: 'Scan'
    jobs:
      - template: scan.yml
        parameters:
          BuildSourceDir: '${{ parameters.BuildSourceDir }}'