parameters:
  - name: AppName
    type: string
  - name: BuildSourceDir
    type: string

jobs:
- job: build
  displayName: 'Run Build'
  steps:
  - script: env | sort
    displayName: 'Environment / Context'
  - script: |
      echo "Key1: ${{ parameters.AppName }}"
      echo "Key1: ${{ parameters.BuildSourceDir}}"
    displayName: 'Display object keys and values'

- job: quality_check
  displayName: 'Run SonarQube Analysis'
  steps:
  - script: |
      echo "Key1: ${{ parameters.AppName }}"
      echo "Key1: ${{ parameters.BuildSourceDir}}"
    displayName: 'Display object keys and values'

- job: vulnerability_check
  displayName: 'Run WhiteSource Analysis'
  steps:
  - script: |
      echo "Key1: ${{ parameters.AppName }}"
      echo "Key1: ${{ parameters.BuildSourceDir}}"
    displayName: 'Display object keys and values'

- job: secrets_check
  displayName: 'Run GitLeaks Analysis'
  steps:
  - script: |
      echo "Key1: ${{ parameters.AppName }}"
      echo "Key1: ${{ parameters.BuildSourceDir}}"
    displayName: 'Display object keys and values'

- job: sca_check
  displayName: 'Run Checkov Analysis'
  steps:
  - template: scan/checkov.yml

- job: security_check
  displayName: 'Run Trivy Analysis'
  steps:
  - template: scan/trivy.yml