parameters:
  - name: IsScan
    type: boolean

jobs:
- job: secrets_check
  displayName: 'Run GitLeaks Analysis'
  steps:
  - template: scan/gitleaks.yml

- job: sca_check
  displayName: 'Run Checkov Analysis'
  steps:
  - template: scan/checkov.yml

- job: security_check
  displayName: 'Run Trivy Analysis'
  steps:
  - template: scan/trivy.yml